apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backstage-backend-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/kcufl/back
    targetRevision: HEAD
    path: deploy/backend/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true